services:
  backend:
    container_name: app_backend_prod
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - video_storage:/app/videos
    networks:
      - app_network

volumes:
  video_storage:

networks:
  app_network:
    driver: bridge